[package]
name = "isred"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
src = "src/client.rs"

[[bin]]
name = "server"
src = "src/server.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
